name: Rental Service CI

on:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      LAZARUS_DIR: /usr/bin 
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Install Free Pascal and Lazarus
        run: |
            sudo apt update
            sudo apt install -y fpc fpc-source lazarus

      - name: Build Console Application
        run: lazbuild -Bq src/applications/console/RentalServiceConsole.lpi
        
      - name: Build Unit TestRunner Application
        run: lazbuild -Bq tests/RentalServiceTestRunner.lpi --add-package src/rentalservice.lpk

      - name: Run Unit Tests
        run: ./tests/RentalServiceTestRunner "--all" "--format=plain"
