name: Rental Service CI

on:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Install Lazarus
        uses: gcarreno/setup-lazarus@v3

      - name: Build Console Application
        run: lazbuild -Bq src/applications/console/RentalServiceConsole.lpi
        
      - name: Build Unit TestRunner Application
        run: lazbuild -Bq tests/RentalServiceTestRunner.lpi

      - name: Run Unit Tests
        run: bin/RentalServiceTestRunner "--all" "--format=plain"
