name: Rental Service CI

on:
  pull_request:
    branches:
      - main
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Install Free Pascal and Lazarus
        run: |
            sudo apt update
            sudo apt install -y fpc fpc-source lazarus

      - name: Build Console Application
        run: lazbuild -B src/applications/console/RentalServiceConsole.lpi
        
      - name: Build Unit TestRunner Application
        run: lazbuild -B -r tests/RentalServiceTestRunner.lpi

      - name: Run Unit Tests
        run: ./tests/RentalServiceTestRunner "--all" "--format=plain"
